#!/bin/bash
echo "Starting the swarm..."
docker swarm init
echo "Press any key when you are done adding workers to this swarm."
read -n 1 -s
echo "The following nodes are part of this swarm."
docker node ls
echo "Press any key to continue..."
read -n 1 -s
echo "Deploying application..."
docker stack deploy --compose-file docker-compose.yml snmpd
sleep 60
echo "Done."
echo "The following IPs are avaliable for consulting:"
./get-ip
echo "Type the desired IP..."
read ipadress
echo "Launching application..."
python main.py $ipadress
