version: "3.3"

services:
    snmpd:
        image: polinux/snmpd
        ports:
        - "161:161/udp"
        deploy:
            replicas: 2
            restart_policy:
                condition: none

    firefox:
        image: jlesage/firefox
        shm_size: '64m'
        ports:
        - "5800:5800"
        volumes:
        - "/docker/appdata/firefox:/config:rw"
        deploy:
            replicas: 2
            restart_policy:
                condition: none

